### ISSUE TITLE
Allow `ignore` to accept a function?

### ISSUE THREAD

**Issue by cheapsteak** [syntax-tree/hast-util-find-and-replace#1]
### Subject of the feature

I would like want to fine-tune the `ignore` section of a findAndReplace to ignore replacing things inside e.g. something that has a specific class name; would be nice if i could specify a function so i can customize whether to ignore a node

### Problem

only being able to specify tagNames to ignore doesn't give me the granularity i need to ignore the things i want

### Expected behaviour

I'd like to be able to pass in a function to `ignore`, e.g. 

```ts
ignore: (node: Node) => boolean
```

### Alternatives

Can't think of any

**Comment by wooorm** [comment]
It may make sense to update [`hast-util-is-element`](https://github.com/syntax-tree/hast-util-is-element) to work more like [`unist-util-is`](https://github.com/syntax-tree/unist-util-is). It’s probably what folks expect, and would automatically solve this issue.

I do wonder about what `Object` would mean though. Properties check maybe? `isElement(node, {id: 'some-id'})`. Or we can ignore that for now.

**Comment by cheapsteak** [comment]
As long as it can support some kind of selector that's more specific than an entire HTML tag then that would work :)

**Comment by wooorm** [comment]
See https://github.com/syntax-tree/hast-util-find-and-replace/pull/2#issuecomment-678221759
