### ISSUE TITLE
Very particular situation results in some text not being replaced

### ISSUE THREAD

**Issue by 0xR** [syntax-tree/hast-util-find-and-replace#3]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3 and 4

### Link to runnable example

https://codesandbox.io/s/hast-replace-error-fzuxo3?file=/error.spec.js

### Steps to reproduce

The code sandbox has a broken test. It should not be broken.

### Expected behavior

Both replaceme instances should be replaced.

### Actual behavior

The first "replaceme"  instance is replaced the 2nd bold instance of "replaceme" is not replaced. If I move the bold text earlier in the sentence there is no issue. If I make the text not bold there is also no issue.

I had trouble finding the bug in the sourcecode of this package. Maybe you can help out.

### Runtime

Node v16, Node v14

### Package manager

npm v7

### OS

Linux

### Build and bundle tools

Webpack, Parcel

**Comment by wooorm** [comment]
Managed to narrow it down a bit.

1. It also occurs in `mdast-util-find-and-replace`
2. Here are some more cases. `true` means works, `false` means fails:
  ```
  ['x x', true],
  ['*x* x', true],
  ['*x* x x', true],
  ['x *x*', false],
  ['x *x* x', false],
  ['x x *x*', false]
  ```
3. I believe the [`index` that’s returned here](https://github.com/syntax-tree/hast-util-find-and-replace/blob/bf92853d8f82eed404643374b45f8921202d12b4/index.js#L168) after replacing is wrong: the `text` *inside* emphasis(/strong) is not checked.

**Comment by wooorm** [comment]
I’m off for now and focussing on non-issues this month, so might be a while to get to this!

**Comment by 0xR** [comment]
As a workaround I created my own plugin that does not seem to have the bug.
Maybe it's useful for someone reading this:

```typescript
function isText(node: Node): node is Text {
  return (node as Text).type === 'text';
}

function makeText(value: string): Text {
  return {
    type: 'text',
    value,
  };
}

export const rehypeReplaceRegex: Plugin<
  [{ regex: RegExp; replacer: (match: string) => Element | string }]
> = ({ replacer, regex }) => (tree) => {
  unistFlatMap(tree, (node, index, parent) => {
    if (isText(node)) {
      const match = node.value.match(regex);
      if (!match) {
        return [node];
      }
      const split = node.value.split(regex);
      const result: (Text | Element)[] = [];
      split.forEach((nonMatch, i) => {
        const precedingMatch = match[i - 1];
        if (precedingMatch) {
          const replacement = replacer(precedingMatch);
          if (typeof replacement === 'string') {
            result.push(makeText(replacement));
          } else {
            result.push(replacement);
          }
        }
        if (nonMatch) {
          result.push(makeText(nonMatch));
        }
      });
      return result;
    }
    return [node];
  });
};
```

**Comment by wooorm** [comment]
Found it! P.S. Your deps are out of date!
