### ISSUE TITLE
Allow searching text within style property or style tag

### ISSUE THREAD

**Issue by evgimov** [syntax-tree/hast-util-find-and-replace#5]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

```
The findAndReplace function is not working with style property and style tag.
Example: 
const doc = <html><head><style>main {color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;}</style></head><body><main>Subject line: Test Template<br><p><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Hi {{shomare}}, </span></p>
<p><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Version 2 Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template. </span><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template. </span><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template. </span><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template. </span><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template.. </span><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template....</span><br></p>
<ol>
<li><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template.</span></li>
<li><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template.</span></li>
<li><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template.</span></li>
</ol>
<p></p>
<p></p>
<p><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">Thanks.</span></p>
</main></body></html>'
const hast = fromDom(doc)
findAndReplace(hast, [[/font-family:\s*(.+?(?=;));/gi, '']], undefined, { ignore: ['title', 'script', 'svg', 'math']})
console.log("toHtml", toHtml(hast))
```
Results:
<html><head><style>main {color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;}</style></head><body><main>Subject line: Test Template<br><p><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Hi {{shomare}}, </span></p>
<p><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Version 2 Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template. </span><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template. </span><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template. </span><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template. </span><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template.. </span><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template....</span><br></p>
<ol>
<li><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template.</span></li>
<li><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template.</span></li>
<li><span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Create the fields for your custom setting. The data in these fields are cached with the application.</span><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">This is a test template.</span></li>
</ol>
<p></p>
<p></p>
<p><span style="color: rgba(0,0,0,0.87);background-color: rgb(255,255,255);font-size: 13px;">Thanks.</span></p>
</main></body></html>

### Solution

It should find all font-family styles and remove them within the script tag and all the style properties on different types of nodes.
Input:
`<head><style>main {color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;</style></head>`

and

`<span style="color: rgb(60,61,62);background-color: rgb(255,255,255);font-family: Helvetica;">Version 2 Create the fields for your custom setting. The data in these fields are cached with the application.</span>`

Output:
`<head><style>main {color: rgb(60,61,62);background-color: rgb(255,255,255);</style></head>`

and

`<span style="color: rgb(60,61,62);background-color: rgb(255,255,255);>Version 2 Create the fields for your custom setting. The data in these fields are cached with the application.</span>`

### Alternatives

I don't think of any right now

**Comment by wooorm** [comment]
Hey Evghenii. This package is intended for the text between elements. If you want to find-and-replace `style` attributes, create your own utility:

```js
import {visit} from 'unist-util-visit'

visit(tree, function (node) {
  if (
    node.type === 'element' &&
    node.tagName === 'style' &&
    node.properties &&
    typeof node.properties.style === 'string'
  ) {
    node.properties.style = node.properties.style.replace(/pattern/g, 'replace')
  }
})
